nav:
- identifier: main
  name: main page
  url: "https://blog.agramakov.me"
  weight: -110

link:
- identifier: about
  name: About me
  url: https://agramakov.me
  weight: -110

- identifier: zakhar
  name: Zakhar on hackaday.io
  url: https://zakhar.agramakov.me
  weight: -110
  
- identifier: blog_technical@github
  name: github.com/an-dr/blog_technical
  url: https://github.com/an-dr/blog_technical
  weight: -110
